# Generated by Django 4.x.x on 2025-12-03 
# (Tùy thuộc vào thời gian thực tế của bạn)

from django.db import migrations, models
import django.db.models.deletion


# --- HÀM TẠO BRAND MẶC ĐỊNH TRƯỚC KHI THÊM FK ---
def create_default_brand(apps, schema_editor):
    Brand = apps.get_model('app', 'Brand')
    
    # Tạo đối tượng Brand ID=1
    # Lưu ý: Chúng ta không dùng get_or_create vì nó phức tạp trong migration
    if not Brand.objects.filter(id=1).exists():
        Brand.objects.create(
            id=1,
            name='Chưa Phân Loại (Default)',
            slug='chua-phan-loai'
        )

# --- HÀM XÓA BRAND MẶC ĐỊNH SAU KHI XONG MIGRATION (LƯU Ý: KHÔNG CẦN THIẾT) ---
# def delete_default_brand(apps, schema_editor):
#     Brand = apps.get_model('app', 'Brand')
#     Brand.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Đã cập nhật phụ thuộc sang file 0002_product_image.py
        ('app', '0002_product_image'), 
    ]

    operations = [
        # 1. TẠO MODEL BRAND (từ lệnh makemigrations)
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand_logos')),
            ],
        ),

        # 2. CHẠY PYTHON ĐỂ TẠO BRAND ID=1 (ĐỂ TRÁNH LỖI FK)
        migrations.RunPython(create_default_brand, migrations.RunPython.noop),

        # 3. THÊM TRƯỜNG BRAND VÀO PRODUCT (từ lệnh makemigrations)
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
        
        # NOTE: Không cần lệnh xóa default brand, vì ta muốn giữ nó lại.
        # Nếu cần, RunPython.noop sẽ không làm gì khi revert migration
    ]