# Generated by Django 4.2 on 2025-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_image_alter_brand_name_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Nhập thông số cách nhau bằng dấu gạch đầu dòng', null=True),
        ),
    ]
