# Generated by Django 5.2.8 on 2025-12-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_image_alter_brand_name_alter_brand_slug_and_more'),
        ('app', '0004_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
    ]
