# Generated by Django 4.2 on 2025-12-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_added']},
        ),
    ]
