# Generated by Django 5.2.8 on 2026-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('new_arrival', '🔥 Sản phẩm mới'), ('vip', '💎 Khách hàng thân thiết'), ('new_user', '👋 Khách hàng mới'), ('holiday', '🎉 Dịp lễ tết'), ('normal', '🎫 Thông thường')], default='normal', max_length=20, verbose_name='Loại khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
