# Generated by Django 5.2.8 on 2026-01-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_promotion_promotion_type_alter_review_rating'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='target_brands',
            field=models.ManyToManyField(blank=True, related_name='brand_promotions', to='app.brand', verbose_name='Áp dụng cho Hãng'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='group_promotions', to='auth.group', verbose_name='Áp dụng cho Nhóm khách hàng'),
        ),
    ]
