# Generated by Django 5.2.8 on 2026-01-02 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_promotion_target_brands_promotion_target_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên hạng')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='target_groups',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('normal', '🎫 Thông thường'), ('new_arrival', '🔥 Sản phẩm mới'), ('vip', '💎 Khách hàng thân thiết'), ('flash_sale', '⚡ Flash Sale'), ('new customer', '🌟 Khách hàng mới'), ('holiday', '🎉 Dịp lễ hội')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_brands',
            field=models.ManyToManyField(blank=True, related_name='brand_promotions', to='app.brand', verbose_name='Toàn bộ hãng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_products',
            field=models.ManyToManyField(blank=True, related_name='product_promotions', to='app.product', verbose_name='Sản phẩm cụ thể'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='private_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng cụ thể'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customertype', verbose_name='Hạng thành viên'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_customer_types',
            field=models.ManyToManyField(blank=True, related_name='type_promotions', to='app.customertype', verbose_name='Hạng thành viên áp dụng'),
        ),
    ]
