# Generated by Django 4.2 on 2026-01-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_vnpay_review_ai_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=100, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ (Latitude)')),
                ('longitude', models.FloatField(verbose_name='Kinh độ (Longitude)')),
                ('region', models.CharField(choices=[('MB', 'Miền Bắc'), ('MT', 'Miền Trung'), ('MN', 'Miền Nam')], default='MN', max_length=50, verbose_name='Khu vực')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Đánh giá TB'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pin & Sạc'),
        ),
        migrations.AddField(
            model_name='product',
            name='chip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chip xử lý'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camera trước'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá gốc (Mặc định)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camera sau'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Màn hình'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0, verbose_name='Đã bán'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.IntegerField(default=0, verbose_name='Giới hạn số lượng (0 là không giới hạn)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.brand', verbose_name='Hãng sản xuất'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán (Mặc định)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('normal', 'Thông thường'), ('new_arrival', 'Sản phẩm mới'), ('vip', 'Khách hàng thân thiết'), ('flash_sale', 'Flash Sale'), ('new_customer', 'Khách hàng mới'), ('holiday', 'Dịp lễ hội')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.CharField(max_length=50, verbose_name='Dung lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán riêng')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá gốc riêng')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.product')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Các biến thể (Dung lượng/Màu...)',
            },
        ),
    ]
