# Generated by Django 4.2 on 2026-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_payment_vnpay_store_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Tích cực'), (0, 'Tiêu cực'), (-1, 'Trung lập')], null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-date_added'], name='app_review_product_235c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'sentiment'], name='app_review_product_cefcf7_idx'),
        ),
    ]
