# Generated by Django 4.2 on 2026-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_store_remove_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_rating',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
